### ISSUE TITLE
SpringBootTest - Tracing does not seem to work when called from test functions

### ISSUE THREAD

**Issue by krodyrobi** [micrometer-metrics/tracing#413]
For some reason that eludes me, the same piece of code that works within the controllers, or from a cli runners does not work when called from a test function.

I'd expect the wrapping span / trace to be honored and it's baggages be available like in other cases.
Made sure the automatic context propagation hook gets called even for tests and it does.
Used the autoconfiguration annotation although it didn't seem to do anything as beans where already present without it.

Any ideas why this would happen?
https://github.com/krodyrobi/mdc-replicator/tree/test-observation

**Comment by jonatan-ivanov** [comment]
Could you pease make sure that `Hooks.enableAutomaticContextPropagation()` is surely called?
E.g.: `@SpringBootTest(useMainMethod = ALWAYS)`

**Comment by krodyrobi** [comment]
I've tried adding the useMainMethod, using static {} inside the main class, beforeAll, even within the test first statement.
All the ifs inside the hook seem to pass and yet I'm not seing any capturing.

**Comment by krodyrobi** [comment]
@jonatan-ivanov 
I've tried adding the useMainMethod, using static {} inside the main class, beforeAll, even within the test as a first statement.
All the ifs inside the hook seem to pass and yet I'm not seing any capturing.

**Comment by krodyrobi** [comment]
I have a feeling it’s not from the hook, but from the observation registry, do trace spans created create an observation if it is missing?

If I wrap my code in `Observation.start(name, registry).observe(<span code>)` then it seems like they propagate.
But it’s weird as during a single thread execution the tracer code is enough.

Is this expected?
Tried it in snapshot and in the latest spring boot 3 stable release and it behaves the same way.

**Comment by krodyrobi** [comment]
I believe #412 also is hitting this behaviour.

**Comment by krodyrobi** [comment]
I believe #412 is also seing the propagation fail when the observation is not explicitly started

**Comment by marcingrzejszczak** [comment]
Can you check with the latest snapshots? I fixed #412

**Comment by krodyrobi** [comment]
@marcingrzejszczak
Tried using 1.3.0-SNAPSHOT bom

```
    implementation(platform("org.springframework.boot:spring-boot-dependencies:3.2.1-SNAPSHOT"))

    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-web")

    implementation(platform("io.micrometer:micrometer-tracing-bom:latest.integration"))
    implementation("io.micrometer:micrometer-tracing-bridge-brave")
    implementation("io.projectreactor:reactor-core-micrometer")

    implementation("com.squareup.okhttp3:okhttp:4.10.0")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("io.projectreactor:reactor-test")
```

It seems that the controller and the @scheduled started to behave as expected.
The tests however still do not create an observation per test. Is there an extension that I missed for it?

**Comment by marcingrzejszczak** [comment]
There is an open issue about this https://github.com/spring-projects/spring-boot/issues/38796

So can we close this and think about the test extensions instead?
